# -*- coding: utf-8 -*-
"""logger_setup.py.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CeLnR8t7TKOU6rv_Z8ZKG3aVAKveiMT3
"""

# logger_setup.py
import logging

def setup_logger():
    logger = logging.getLogger(__name__.split('.')[0]) # Get root logger for the project
    logger.setLevel(logging.INFO)

    if not logger.hasHandlers():
        handler = logging.StreamHandler()
        formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
        handler.setFormatter(formatter)
        logger.addHandler(handler)
    return logger

# Инициализируем логгер при импорте модуля, чтобы он был доступен сразу
logger = setup_logger()